###
 # VGScoreboardPing
 # Copyright (C) 2013 Caio Cogliatti Jabulka (Jabulba) <http://www.jabulba.com>
 # 
 # This file is part of VGScoreboardPing.
 # VGScoreboardPing was originally a module of VG Server Manager(All Right Reserved until public release)
 # 
 # VGScoreboardPing is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 # 
 # VGScoreboardPing is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
 # 
 # You should have received a copy of the GNU General Public License
 # along with VGScoreboardPing.  If not, see <http://www.gnu.org/licenses/>.
 ##

 #The time in ticks to update the scoreboard
period: 100

#Attempt to use other plugins scoreboard. Set this to true if you have other plugins using the scoreboard.
compatibility-mode: false

#Change if you get an error about not being able to find the ping field. for more info: http://dev.bukkit.org/bukkit-plugins/vg-scoreboard-ping/pages/how-it-works/
fallback-field: lastPing

#You can opt-out from metrics by setting the value to true. Metrics can help devs out! Disable only if you really need to!
#Optionally you can globally opt-out from metrics by editing "plugins/PluginMetrics/config.yml" and changing opt-out to true.
#You can check the information here: http://mcstats.org/plugin/VGScoreboardPing
metrics-opt-out: false